{% set name = "pecos" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sandialabs/pecos/archive/{{ version }}.zip
  sha256: f6ea68679fc44783ebd00f7067fee5bc6f88c3a63d9fd7fb12f4ba99d57a8837

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas >=0.18.0
    - numpy >=1.10.4
    - jinja2
    - matplotlib-base

test:
  imports:
    - pecos

about:
  home: https://github.com/sandialabs/pecos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Data quality control and fault detection'
  doc_url: https://pecos.readthedocs.io/

extra:
  recipe-maintainers:
    - kaklise
