{% set name = "pecos" %}
{% set version = "1.0.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sandialabs/pecos/archive/{{ version }}.zip
  sha256: 34316f34e135d896a21f847dfe2509fd7f26800b24496767584d133de7946756

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=0.18.0
    - numpy >=1.10.4
    - jinja2
    - matplotlib-base
    - pytest

test:
  requires:
    - python {{ python_min }}
  imports:
    - pecos

about:
  home: https://github.com/sandialabs/pecos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Data quality control and fault detection'
  doc_url: https://pecos.readthedocs.io/

extra:
  recipe-maintainers:
    - kaklise
